### ISSUE TITLE
검색 기능: 에러 사항 개선 / 리팩토링

### ISSUE THREAD

**Issue by Hyeondoonge** [Hyeondoonge/Alog#7]
## ☀️  개요
이전 이슈에 포함된 기능 구현 중 발견한 에러사항들 개선하기 위해 구현해야함

###
- [x]  Loading 컴포넌트 렌더링 위치 개선
- [x]  포스트 필터링 http 통신 구현 (서버에서 필터링 처리)
 : 키워드 입력과 마찬가지로 필터링 시에도 페이징이 적용되므로, 기존 클라이언트가 필터링 처리 -> 서버에서 필터링과 함께 페이징 처리
- [x] 🔥 Search 컴포넌트 재검토 및 리팩토링 🔥
- [ ] 포스트 렌더링 도중 추가 또는 삭제가 발생할 때 totalCount 상태 관련한 문제(1. 무한 페칭 2. 노 페칭)
- [ ] 무효해진 요청에 관한 처리(ex. ?)
- [x] localStorage 이용해서 선택된 필터 기억하기 - 앱: bool, localStorage: string ??
- [x] debounce 구현
- [x] 포스트 렌더링 시 로고/검색바 컴포넌트 width 좁아지는 문제

## 📌  개선 사항
없음

**Comment by ondal1997** [comment]
Search 컴포넌트 개발은 상태 관리 실력을 향상시켜줄 좋은 기회라고 생각되네요!
부디 차분하게 정복하시길..!
